app:
  name: "AI Gap Finder"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8001
  debug: true

llm:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 2000
  timeout: 30

pdf:
  max_file_size: 10485760  # 10MB in bytes
  allowed_extensions: [".pdf"]

embedding:
  model: "text-embedding-ada-002"
  chunk_size: 1000
  chunk_overlap: 200

arxiv:
  base_url: "http://export.arxiv.org/api/query"
  max_results: 10

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
